// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5mdFzk35LQj8_IQCPj5SNEDeuPJfGi8',
    appId: '1:1063572891256:web:8ba3323847d85af8fc6f8d',
    messagingSenderId: '1063572891256',
    projectId: 'tomconn-8c66d',
    authDomain: 'tomconn-8c66d.firebaseapp.com',
    storageBucket: 'tomconn-8c66d.appspot.com',
    measurementId: 'G-QD8Y810X7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCseTjWTCOKJNHWWJsSA0D9A7fn-IDQDlY',
    appId: '1:1063572891256:android:29061836028e1e29fc6f8d',
    messagingSenderId: '1063572891256',
    projectId: 'tomconn-8c66d',
    storageBucket: 'tomconn-8c66d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAL2xemYKPiUgjdIWlgn-zoxRfNAG4VT0',
    appId: '1:1063572891256:ios:75075b14295993c3fc6f8d',
    messagingSenderId: '1063572891256',
    projectId: 'tomconn-8c66d',
    storageBucket: 'tomconn-8c66d.appspot.com',
    iosClientId: '1063572891256-bh4gr0p8717vhat07kp7boft415ohd1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomConn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAL2xemYKPiUgjdIWlgn-zoxRfNAG4VT0',
    appId: '1:1063572891256:ios:75075b14295993c3fc6f8d',
    messagingSenderId: '1063572891256',
    projectId: 'tomconn-8c66d',
    storageBucket: 'tomconn-8c66d.appspot.com',
    iosClientId: '1063572891256-bh4gr0p8717vhat07kp7boft415ohd1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tomConn',
  );
}
